DATABASE_URL = "sqlite:///data/financial_market.db"

RAW_DATA_DIR = "data/raw"

RAW_STOCKS_DIR = "data/raw/stocks"
RAW_NEWS_DIR = "data/raw/news"
RAW_ECONOMIC_DIR = "data/raw/economic"

PROCESSED_DATA_DIR = "data/processed"

INDICATORS_DIR = "data/processed/indicators"
SENTIMENT_DIR = "data/processed/sentiment"

HISTORY_PERIOD = "2y"

INTERVAL = "1d"

RSI_WINDOW = 14

MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9

BB_WINDOW = 20
BB_STD = 2

MACD_WEIGHT = 0.50
RSI_WEIGHT = 0.30
BOLLINGER_WEIGHT = 0.20

TECHNICAL_WEIGHT = 0.40
NEWS_WEIGHT = 0.25
VOLUME_WEIGHT = 0.15
ECONOMIC_WEIGHT = 0.10
FII_DII_WEIGHT = 0.10

REPO_WEIGHT = 0.40
GDP_WEIGHT = 0.35
INFLATION_WEIGHT = 0.25

VOLUME_LOOKBACK = 20

VERY_HIGH_VOLUME = 2.0
HIGH_VOLUME = 1.5
LOW_VOLUME = 0.75
VERY_LOW_VOLUME = 0.50

STRONG_BUY_THRESHOLD = 0.75
BUY_THRESHOLD = 0.25

HOLD_MIN = -0.25
HOLD_MAX = 0.25

SELL_THRESHOLD = -0.75

HIGH_CONFIDENCE = 85
MEDIUM_CONFIDENCE = 65
LOW_CONFIDENCE = 45

FINBERT_MODEL = "ProsusAI/finbert"

EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"

LOG_LEVEL = "INFO"

TOP_STOCKS_LIMIT = 10

MAX_NEWS_PER_SOURCE = 100

TECHNICAL_WEIGHT = 0.40

NEWS_WEIGHT = 0.25

VOLUME_WEIGHT = 0.15

ECONOMIC_WEIGHT = 0.10

FII_DII_WEIGHT = 0.10

MACD_WEIGHT = 0.50

RSI_WEIGHT = 0.30

BOLLINGER_WEIGHT = 0.20

REPO_WEIGHT = 0.40

GDP_WEIGHT = 0.35

INFLATION_WEIGHT = 0.25

BUY = "BUY"
SELL = "SELL"
HOLD = "HOLD"

STRONG_BUY = "STRONG BUY"
STRONG_SELL = "STRONG SELL"

BULLISH = "Bullish"
BEARISH = "Bearish"
NEUTRAL = "Neutral"

LOW = "Low"
MEDIUM = "Medium"
HIGH = "High"

