"""
FORESIGHT AI market report builder.

Exports a professional current-market report. Historical rows remain available
in SQLite, but report calculations use latest snapshots and recency-aware
scores generated by the risk engines.
"""

import json
from pathlib import Path
import shutil

import pandas as pd
from sqlalchemy import create_engine

from src.utils.freshness import bounded_mean, latest_per_group, latest_rows, iso_date


engine = create_engine("sqlite:///data/financial_market.db")
REPORT_FOLDER = Path("reports")
REPORT_FOLDER.mkdir(exist_ok=True)

WEIGHTS = {
    "Technical": 0.40,
    "News": 0.25,
    "Volume": 0.15,
    "Economic": 0.10,
    "Institutional": 0.10,
}


def load_tables():
    return {
        "technical": pd.read_sql("SELECT * FROM technical_scores", engine),
        "news": pd.read_sql("SELECT * FROM news_scores", engine),
        "volume": pd.read_sql("SELECT * FROM volume_scores", engine),
        "economic": pd.read_sql("SELECT * FROM economic_scores", engine),
        "institutional": pd.read_sql("SELECT * FROM fii_dii_scores", engine),
        "risk": pd.read_sql("SELECT * FROM risk_scores", engine),
    }


def current_views(data):
    institutional = data["institutional"].copy()
    if not institutional.empty:
        institutional = institutional.drop_duplicates(
            ["date", "client_type"],
            keep="last",
        )

    return {
        "technical": latest_per_group(
            data["technical"],
            group_column="ticker",
            required_columns=["technical_score"],
        ),
        "volume": latest_per_group(
            data["volume"],
            group_column="ticker",
            required_columns=["volume_score", "volume_ratio"],
        ),
        "economic": latest_rows(data["economic"]),
        "institutional": latest_rows(institutional),
        "risk": latest_rows(data["risk"]),
        "news": data["news"].copy(),
    }


def market_risk(score, agreement, confidence):
    magnitude = abs(float(score))
    if confidence >= 75 and agreement >= 80 and magnitude >= 0.50:
        return "LOW"
    if confidence >= 55 and agreement >= 60:
        return "MEDIUM"
    return "HIGH"


def executive_summary(views):
    risk = views["risk"].iloc[-1]
    return {
        "date": risk["date"],
        "recommendation": risk["signal"],
        "overall_score": float(risk["final_score"]),
        "confidence": float(risk["confidence"]),
        "agreement": float(risk["agreement_score"]),
        "market_risk": market_risk(
            risk["final_score"],
            risk["agreement_score"],
            risk["confidence"],
        ),
        "reason": risk["reason"],
    }


def score_breakdown(views):
    risk = views["risk"].iloc[-1]
    mapping = {
        "Technical": "technical_score",
        "News": "news_score",
        "Volume": "volume_score",
        "Economic": "economic_score",
        "Institutional": "fii_score",
    }
    scores = {}
    for module, column in mapping.items():
        score = float(risk[column])
        weight = WEIGHTS[module]
        scores[module] = {
            "score": score,
            "weight": int(weight * 100),
            "contribution": round(score * weight, 3),
        }
    return scores


def technical_analysis(views):
    df = views["technical"]
    if df.empty:
        return {}

    best = df.sort_values("technical_score", ascending=False).iloc[0]
    worst = df.sort_values("technical_score").iloc[0]
    return {
        "as_of": iso_date(df["_parsed_date"].max()),
        "tracked_stocks": int(df["ticker"].nunique()),
        "average_score": round(bounded_mean(df["technical_score"]), 3),
        "buy_signals": int(df["signal"].isin(["BULLISH", "STRONGLY BULLISH"]).sum()),
        "sell_signals": int(df["signal"].isin(["BEARISH", "STRONGLY BEARISH"]).sum()),
        "average_confidence": round(bounded_mean(df["confidence"]), 2),
        "best_stock": best["ticker"],
        "best_score": float(best["technical_score"]),
        "worst_stock": worst["ticker"],
        "worst_score": float(worst["technical_score"]),
    }


def news_analysis(views):
    df = views["news"]
    if df.empty:
        return {}

    best = df.sort_values(["news_score", "confidence"], ascending=False).iloc[0]
    worst = df.sort_values(["news_score", "confidence"]).iloc[0]
    latest_article = ""
    if "latest_article_at" in df.columns:
        latest_article = str(pd.to_datetime(df["latest_article_at"], errors="coerce").max())

    return {
        "latest_article_at": latest_article,
        "scored_sectors": int(df["sector"].nunique()),
        "average_score": round(bounded_mean(df["news_score"]), 3),
        "positive_articles": int(df["positive_articles"].sum()),
        "neutral_articles": int(df["neutral_articles"].sum()),
        "negative_articles": int(df["negative_articles"].sum()),
        "article_count": int(df.get("article_count", pd.Series(dtype=float)).sum()),
        "average_confidence": round(bounded_mean(df["confidence"]), 2),
        "best_sector": best["sector"],
        "best_score": float(best["news_score"]),
        "worst_sector": worst["sector"],
        "worst_score": float(worst["news_score"]),
    }


def volume_analysis(views):
    df = views["volume"]
    if df.empty:
        return {}

    highest = df.sort_values("volume_ratio", ascending=False).iloc[0]
    return {
        "as_of": iso_date(df["_parsed_date"].max()),
        "tracked_stocks": int(df["ticker"].nunique()),
        "average_score": round(bounded_mean(df["volume_score"]), 3),
        "average_ratio": round(bounded_mean(df["volume_ratio"]), 2),
        "average_confidence": round(bounded_mean(df["confidence"]), 2),
        "highest_volume_stock": highest["ticker"],
        "highest_volume_ratio": float(highest["volume_ratio"]),
    }


def economic_analysis(views):
    df = views["economic"].iloc[-1]
    return {
        "as_of": df["date"],
        "repo_rate": float(df["repo_rate"]),
        "gdp_growth": float(df["gdp_growth"]),
        "inflation": float(df["inflation"]),
        "economic_score": float(df["economic_score"]),
        "signal": df["signal"],
        "confidence": float(df["confidence"]),
        "reason": df.get("reason", ""),
    }


def institutional_analysis(views):
    df = views["institutional"]
    if df.empty:
        return {}

    return {
        "as_of": df["date"].iloc[-1],
        "net_flow": float(df["net_value"].sum()),
        "average_score": round(bounded_mean(df["flow_score"]), 3),
        "buyers": int((df["net_value"] > 0).sum()),
        "sellers": int((df["net_value"] < 0).sum()),
        "average_confidence": round(bounded_mean(df["confidence"]), 2),
    }


def data_quality(views):
    risk = views["risk"].iloc[-1]
    keys = [
        "technical_rows",
        "volume_rows",
        "news_rows",
        "economic_rows",
        "fii_rows",
        "technical_date",
        "volume_date",
        "news_date",
        "economic_date",
        "fii_date",
    ]
    return {key: risk[key] for key in keys if key in risk.index}


def generate_reasoning(summary, scores, quality):
    lines = [
        (
            f"FORESIGHT AI recommends {summary['recommendation']} with a current "
            f"market score of {summary['overall_score']:.3f}, confidence of "
            f"{summary['confidence']:.2f}%, and agreement of {summary['agreement']:.1f}%."
        ),
        "",
        (
            "This report uses latest-per-instrument technical and volume snapshots, "
            "latest macro and institutional dates, and recency-weighted news sentiment."
        ),
        "",
        "Module interpretation:",
    ]

    for module, values in scores.items():
        score = values["score"]
        contribution = values["contribution"]
        if score >= 0.20:
            tone = "supportive"
        elif score <= -0.20:
            tone = "negative"
        else:
            tone = "neutral"
        lines.append(
            f"- {module}: {tone} score {score:.3f}, contribution {contribution:.3f}."
        )

    lines.extend(
        [
            "",
            (
                f"Freshness: technical {quality.get('technical_date', 'n/a')}, "
                f"volume {quality.get('volume_date', 'n/a')}, "
                f"news {quality.get('news_date', 'n/a')}, "
                f"economic {quality.get('economic_date', 'n/a')}, "
                f"institutional {quality.get('fii_date', 'n/a')}."
            ),
            "",
            (
                f"Risk is classified as {summary['market_risk']} because this combines "
                "model confidence, signal agreement, and score magnitude."
            ),
        ]
    )

    return "\n".join(lines)


def dashboard_payload(summary, scores, report):
    sectors = []
    news_df = pd.read_sql("SELECT * FROM news_scores ORDER BY sector_rank", engine)
    for _, row in news_df.head(5).iterrows():
        sectors.append({"name": row["sector"], "score": float(row["news_score"])})

    recent_news = pd.read_sql(
        """
        SELECT title, sentiment, confidence
        FROM news_sentiment
        ORDER BY published_at DESC
        LIMIT 5
        """,
        engine,
    )

    return {
        "recommendation": summary["recommendation"],
        "overall_score": summary["overall_score"],
        "confidence": summary["confidence"],
        "risk": summary["market_risk"],
        "agreement": summary["agreement"],
        "metrics": {
            "technical": scores["Technical"]["score"],
            "news": scores["News"]["score"],
            "volume": scores["Volume"]["score"],
            "economic": scores["Economic"]["score"],
            "institutional": scores["Institutional"]["score"],
        },
        "chart": build_risk_trend(summary["overall_score"]),
        "reasons": [reason.strip() for reason in summary["reason"].split(",")],
        "ai_explanation": report["ai_reasoning"],
        "sectors": sectors,
        "news": [
            {
                "title": row["title"],
                "sentiment": str(row["sentiment"]).title(),
                "confidence": round(float(row["confidence"]) * 100, 2),
            }
            for _, row in recent_news.iterrows()
        ],
        "data_quality": report["data_quality"],
    }


def build_risk_trend(today_score):
    risk = pd.read_sql("SELECT date, final_score FROM risk_scores ORDER BY date", engine)
    if len(risk) >= 2:
        rows = risk.tail(7)
        return [
            {"day": str(row["date"]), "score": float(row["final_score"])}
            for _, row in rows.iterrows()
        ]

    baseline = [0.28, 0.31, 0.29, 0.34, 0.36, 0.33]
    labels = ["T-6", "T-5", "T-4", "T-3", "T-2", "T-1"]
    return [
        *[{"day": label, "score": value} for label, value in zip(labels, baseline)],
        {"day": "Today", "score": today_score},
    ]


def print_report(summary, scores, report):
    print("\n" + "=" * 80)
    print("                 FORESIGHT AI MARKET REPORT")
    print("=" * 80)
    print(f"Date           : {summary['date']}")
    print(f"Recommendation : {summary['recommendation']}")
    print(f"Overall Score  : {summary['overall_score']:.3f}")
    print(f"Confidence     : {summary['confidence']:.2f}%")
    print(f"Agreement      : {summary['agreement']:.2f}%")
    print(f"Market Risk    : {summary['market_risk']}")
    print("\nScore Breakdown")
    print("-" * 80)
    for module, values in scores.items():
        print(
            f"{module:<15} Score={values['score']:.3f} "
            f"Weight={values['weight']}% Contribution={values['contribution']:.3f}"
        )
    print("\nReasoning")
    print("-" * 80)
    print(report["ai_reasoning"])
    print("=" * 80)


def export_json(report):
    with open(REPORT_FOLDER / "market_report.json", "w", encoding="utf-8") as f:
        json.dump(report, f, indent=4, ensure_ascii=False, default=str)


def export_csv(scores):
    pd.DataFrame(
        [
            {
                "Module": module,
                "Score": values["score"],
                "Weight": values["weight"],
                "Contribution": values["contribution"],
            }
            for module, values in scores.items()
        ]
    ).to_csv(REPORT_FOLDER / "score_breakdown.csv", index=False)


def save_database(summary):
    pd.DataFrame(
        [
            {
                "date": summary["date"],
                "recommendation": summary["recommendation"],
                "overall_score": summary["overall_score"],
                "confidence": summary["confidence"],
                "market_risk": summary["market_risk"],
                "agreement_score": summary["agreement"],
            }
        ]
    ).to_sql("market_reports", con=engine, if_exists="replace", index=False)


def export_dashboard(payload):
    backend_dashboard = Path("data/dashboard.json")
    with open(backend_dashboard, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=4, ensure_ascii=False, default=str)

    frontend_dashboard = Path("../frontend/public/dashboard.json")
    frontend_dashboard.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(backend_dashboard, frontend_dashboard)


def main():
    print("\nGenerating Market Report...\n")

    views = current_views(load_tables())
    summary = executive_summary(views)
    scores = score_breakdown(views)
    quality = data_quality(views)

    report = {
        "executive_summary": summary,
        "score_breakdown": scores,
        "technical_analysis": technical_analysis(views),
        "news_analysis": news_analysis(views),
        "volume_analysis": volume_analysis(views),
        "economic_analysis": economic_analysis(views),
        "institutional_analysis": institutional_analysis(views),
        "data_quality": quality,
        "ai_reasoning": generate_reasoning(summary, scores, quality),
    }

    print_report(summary, scores, report)
    export_json(report)
    export_csv(scores)
    save_database(summary)
    export_dashboard(dashboard_payload(summary, scores, report))

    print("\nMarket report, dashboard JSON, CSV, and SQLite export completed.\n")


if __name__ == "__main__":
    main()
